version: '3'
services:
  web:
    image: odoo:16
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - web:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      # - ../enterprise:/mnt/enterprise
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
volumes:
  web:
  db:
